version: '3.9'

services:
  server:
    image: toastjpg/recipe-server
    container_name: recipe-server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    container_name: recipe-db
    environment:
      POSTGRES_DB: recipe-app
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d recipe-app -h postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
