version: '3.9'

services:
  # later add the server here too and change from connection string to whats in the demo
  # after server development is done tho

  postgres:
    image: postgres:latest
    container_name: recipe-db
    environment:
      POSTGRES_DB: recipe-app
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5432:5432"